import Link from "next/link";

export default function DocsPage() {
  return <main className="information-page">
    <nav className="topbar"><Link className="brand" href="/"><span className="brand-mark">OM</span><strong>OmniMarket</strong></Link><div className="nav-links"><Link href="/how-it-works">How it works</Link><Link href="/portfolio">Portfolio</Link><Link href="/">Open app</Link></div></nav>
    <header className="information-hero"><span className="section-kicker">OMNIMARKET DOCUMENTATION</span><h1>Prediction markets with an evidence trail.</h1><p>OmniMarket is a GenLayer Intelligent Contract for native-GEN, two-outcome markets. The contract owns market state, value accounting, price observations, source receipts, settlement, and refunds.</p></header>
    <div className="information-layout"><aside className="information-index"><a href="#model">Protocol model</a><a href="#lifecycle">Lifecycle</a><a href="#trust">Trust boundaries</a><a href="#api">Contract surface</a></aside><article className="information-content"><section id="model"><span className="section-kicker">01</span><h2>Protocol model</h2><p>Creators publish a question, two outcomes, a deterministic rule, five evidence sources, a close time, and an even GEN seed. Each source URI must be unique and use HTTP(S). Traders attach native GEN to one outcome. Prices are derived from the two on-chain pools.</p></section><section id="lifecycle"><span className="section-kicker">02</span><h2>Lifecycle</h2><div className="information-cards"><div><strong>Open</strong><p>Trading is available until the declared close time.</p></div><div><strong>Locked</strong><p>Anyone can lock after close. A 120-second safety delay protects the evidence window.</p></div><div><strong>Resolved or void</strong><p>Five sources are evaluated independently and require a three-source quorum. Ambiguous or unavailable evidence produces a refundable void state.</p></div></div></section><section id="trust"><span className="section-kicker">03</span><h2>Trust boundaries</h2><p>Market data, prices, positions, and source receipts come from accepted GenLayer contract reads. The live Binance panel is a reference feed only and never participates in settlement. Wallet writes are signed in the browser; the server bridge never receives private keys.</p></section><section id="api"><span className="section-kicker">04</span><h2>Contract surface</h2><p>Read the complete method list in the repository&apos;s <code>API_MANIFEST.md</code>. The source and Bradbury test evidence are linked from the app. Use the <Link href="/how-it-works">how-it-works guide</Link> for the operator and trader workflows.</p></section></article></div>
  </main>;
}
